/**
 * Legacy contract → formal spec migration.
 *
 * Reads contract source files, detects define() calls via simple regex,
 * and generates skeleton formal-spec modules with TODO comments.
 *
 * Spike-level: only detects define() and emits commented skeleton.
 */

import { readFileSync } from 'node:fs';

export interface DetectedContract {
  readonly name: string;
  readonly guards: readonly string[];
  readonly conditions: readonly string[];
  readonly invariants: readonly string[];
  readonly sourceFile: string;
}

/**
 * Detect define() calls in a contract source file and extract metadata.
 * Uses simple regex matching – not a full AST parse.
 */
export function detectContracts(filePath: string): readonly DetectedContract[] {
  const source = readFileSync(filePath, 'utf-8');
  const contracts: DetectedContract[] = [];

  // Match: define<...>('name', ...) or define('name', ...)
  const defineRegex = /define(?:<[^>]*>)?\(\s*['"]([^'"]+)['"]/g;
  let match: RegExpExecArray | null = defineRegex.exec(source);

  while (match !== null) {
    const name = match[1];

    // Extract guard descriptions
    const guards = extractStringArrayItems(
      source,
      /\.guard\(\s*['"]([^'"]+)['"]/g
    );
    // Extract condition descriptions
    const conditions = extractStringArrayItems(
      source,
      /\.condition\(\s*['"]([^'"]+)['"]/g
    );
    // Extract invariant descriptions
    const invariants = extractStringArrayItems(
      source,
      /\.invariant\(\s*['"]([^'"]+)['"]/g
    );

    contracts.push({
      name,
      guards,
      conditions,
      invariants,
      sourceFile: filePath,
    });
    match = defineRegex.exec(source);
  }

  return contracts;
}

function extractStringArrayItems(
  source: string,
  regex: RegExp
): readonly string[] {
  const items: string[] = [];
  let m: RegExpExecArray | null = regex.exec(source);
  while (m !== null) {
    items.push(m[1]);
    m = regex.exec(source);
  }
  return items;
}

/**
 * Generate a skeleton formal-spec TypeScript module from detected contracts.
 */
export function generateSkeleton(
  contracts: readonly DetectedContract[]
): string {
  const lines: string[] = [];

  lines.push('// Generated by seizu migrate legacy');
  lines.push("import { lawSpec, law } from 'seizu/spec';");
  lines.push('');
  lines.push('// TODO: Update target locator to point to your implementation');
  lines.push('// TODO: Add proper generators');
  lines.push('// TODO: Review and update law predicates');
  lines.push('');
  lines.push('export const specs = [');

  for (const contract of contracts) {
    lines.push(`  // Migrated from contract: ${contract.name}`);
    if (contract.guards.length > 0) {
      lines.push(
        `  // Original guards: [${contract.guards.map((g) => `'${g}'`).join(', ')}]`
      );
    }
    if (contract.conditions.length > 0) {
      lines.push(
        `  // Original conditions: [${contract.conditions.map((c) => `'${c}'`).join(', ')}]`
      );
    }
    if (contract.invariants.length > 0) {
      lines.push(
        `  // Original invariants: [${contract.invariants.map((i) => `'${i}'`).join(', ')}]`
      );
    }
  }

  lines.push('] as const;');
  lines.push('');

  return lines.join('\n');
}
