/**
 * Legacy contract → formal spec migration.
 *
 * Reads contract source files, detects define() calls via simple regex,
 * and generates skeleton formal-spec modules with TODO comments.
 *
 * Spike-level: only detects define() and emits skeleton spec objects.
 */

import { readFileSync } from 'node:fs';

export interface DetectedContract {
  readonly name: string;
  readonly guards: readonly string[];
  readonly conditions: readonly string[];
  readonly invariants: readonly string[];
  readonly sourceFile: string;
}

/**
 * Detect define() calls in a contract source file and extract metadata.
 * Uses simple regex matching – not a full AST parse.
 * Clause extraction is scoped to the source slice for each define() match
 * (from the current match index to the next match index) to avoid
 * aggregating clauses from multiple contracts.
 */
export function detectContracts(filePath: string): readonly DetectedContract[] {
  const source = readFileSync(filePath, 'utf-8');
  const contracts: DetectedContract[] = [];

  // Match: define<...>('name', ...) or define('name', ...)
  const defineRegex = /define(?:<[^>]*>)?\(\s*['"]([^'"]+)['"]/g;

  // Collect all match positions first
  const matches: Array<{ name: string; index: number }> = [];
  let m: RegExpExecArray | null = defineRegex.exec(source);
  while (m !== null) {
    matches.push({ name: m[1], index: m.index });
    m = defineRegex.exec(source);
  }

  // For each match, extract clauses from the source slice between this
  // match and the next (or end of file)
  for (let i = 0; i < matches.length; i++) {
    const { name, index } = matches[i];
    const end = i + 1 < matches.length ? matches[i + 1].index : source.length;
    const slice = source.slice(index, end);

    const guards = extractStringArrayItems(
      slice,
      /\.guard\(\s*['"]([^'"]+)['"]/g
    );
    const conditions = extractStringArrayItems(
      slice,
      /\.condition\(\s*['"]([^'"]+)['"]/g
    );
    const invariants = extractStringArrayItems(
      slice,
      /\.invariant\(\s*['"]([^'"]+)['"]/g
    );

    contracts.push({
      name,
      guards,
      conditions,
      invariants,
      sourceFile: filePath,
    });
  }

  return contracts;
}

function extractStringArrayItems(
  source: string,
  regex: RegExp
): readonly string[] {
  const items: string[] = [];
  let m: RegExpExecArray | null = regex.exec(source);
  while (m !== null) {
    items.push(m[1]);
    m = regex.exec(source);
  }
  return items;
}

/**
 * Generate a skeleton formal-spec TypeScript module from detected contracts.
 * Emits one minimal lawSpec/usecaseSpec placeholder per detected contract
 * with TODO markers so the output is immediately actionable.
 */
export function generateSkeleton(
  contracts: readonly DetectedContract[]
): string {
  const lines: string[] = [];

  lines.push('// Generated by seizu migrate legacy');
  lines.push("import { law, lawSpec, usecaseSpec } from 'seizu/spec';");
  lines.push('');
  lines.push('// TODO: Update target locators to point to your implementations');
  lines.push('// TODO: Add proper fast-check generators');
  lines.push('// TODO: Review and refine predicates');
  lines.push('');
  lines.push('export const specs = [');

  for (const contract of contracts) {
    lines.push('');
    lines.push(`  // Migrated from contract: ${contract.name}`);
    if (contract.guards.length > 0) {
      lines.push(
        `  // Original guards: [${contract.guards.map((g) => `'${g}'`).join(', ')}]`
      );
    }
    if (contract.conditions.length > 0) {
      lines.push(
        `  // Original conditions: [${contract.conditions.map((c) => `'${c}'`).join(', ')}]`
      );
    }
    if (contract.invariants.length > 0) {
      lines.push(
        `  // Original invariants: [${contract.invariants.map((inv) => `'${inv}'`).join(', ')}]`
      );
    }

    const specId = contract.name
      .replace(/[^a-zA-Z0-9]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');

    // Emit a lawSpec skeleton when the contract has invariants (pure-function laws)
    // or when there are no guards (no preconditions to model as usecaseSpec given clauses).
    // Otherwise emit a usecaseSpec skeleton for stateful operations.
    const shouldEmitLawSpec =
      contract.invariants.length > 0 || contract.guards.length === 0;
    if (shouldEmitLawSpec) {
      lines.push(`  lawSpec({`);
      lines.push(`    id: 'LAW-${specId}',`);
      lines.push(`    name: '${contract.name}',`);
      lines.push(`    target: { module: 'TODO', export: 'TODO' },`);
      lines.push(`    generators: {`);
      lines.push(`      // TODO: Add fast-check generators`);
      lines.push(`    },`);
      lines.push(`    laws: [`);
      for (const inv of contract.invariants) {
        const lawId = inv
          .replace(/[^a-zA-Z0-9]/g, '-')
          .replace(/-+/g, '-')
          .replace(/^-|-$/g, '');
        lines.push(`      law('${lawId}', '${inv}',`);
        lines.push(`        (_args, _result) => { /* TODO */ return true; }),`);
      }
      if (contract.invariants.length === 0) {
        lines.push(`      // TODO: Define law predicates`);
      }
      lines.push(`    ],`);
      lines.push(`    dependsOn: [],`);
      lines.push(`  }),`);
    } else {
      lines.push(`  usecaseSpec({`);
      lines.push(`    id: 'UC-${specId}',`);
      lines.push(`    name: '${contract.name}',`);
      lines.push(`    target: { module: 'TODO', export: 'TODO' },`);
      lines.push(`    classifyError: (_err) => 'unknown',`);
      lines.push(`    given: [`);
      for (const guard of contract.guards) {
        const guardId = guard
          .replace(/[^a-zA-Z0-9]/g, '-')
          .replace(/-+/g, '-')
          .replace(/^-|-$/g, '');
        lines.push(`      { id: '${guardId}', description: '${guard}',`);
        lines.push(`        predicate: (_ctx) => { /* TODO */ return true; } },`);
      }
      lines.push(`    ],`);
      lines.push(`    ensures: [`);
      for (const cond of contract.conditions) {
        const condId = cond
          .replace(/[^a-zA-Z0-9]/g, '-')
          .replace(/-+/g, '-')
          .replace(/^-|-$/g, '');
        lines.push(`      { id: '${condId}', description: '${cond}',`);
        lines.push(`        predicate: (_ctx) => { /* TODO */ return true; } },`);
      }
      lines.push(`    ],`);
      lines.push(`    invariants: [],`);
      lines.push(`    errors: [],`);
      lines.push(`    effects: [],`);
      lines.push(`    dependsOn: [],`);
      lines.push(`  }),`);
    }
  }

  lines.push('] as const;');
  lines.push('');

  return lines.join('\n');
}
